apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: racs-configs.project.racs
spec:
  group: project.racs
  names:
    plural: racs-configs
    singular: racs-config
    kind: RacsConfig
    shortNames:
      - rconf
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: 
              type: object
              properties:
                selection_policy:
                  type: string 
                  enum: ["random", "load-balancing", "latency"] 
                  default: random
                encoding_parameter_k:
                  type: integer
                  default: 2
                encoding_parameter_n:
                  type: integer
                  default: 3